### ISSUE TITLE
可以设置只显示年月日吗

### ISSUE THREAD

**Issue by xmliu** [mrfluency/Time-Selector#1]
RT，简单看了TimeSelector.java，貌似不行的样子。。。

**Comment by BurnieLiu** [comment]
可以 1.0.9 版本 compile 'com.feezu.liuli:timeselector:1.0.9+'

show之前调用 timeSelector.setMode(TimeSelector.MODE.YMD);
代码 稍后上传

**Comment by zst1303939801** [comment]
显示了年月日选择器，但是输出的结果还是带时分的

**Comment by zst1303939801** [comment]
我又把输出的结果把时分截掉了
