### ISSUE TITLE
设置默认日期

### ISSUE THREAD

**Issue by wangletao** [mrfluency/Time-Selector#14]
能增加选择器的默认日期时间吗，而不是让默认日期时间为设置的起始日期

**Comment by svran** [comment]
我这里有我自己修改了然后打的aar包,需要么?
1.可以设置为默认选中当前系统时间,可以不强制添加起始时间(自动以当前系统时间前后一百年范围),;
2.可以修改文字颜色,
3.可以设置不是特殊情况下每次滚动可不重置后面的数据;
4.代码重构,增强稳定性;

**Comment by TigerChain** [comment]
这个玩意很好改的，你可以改一下。

**Comment by AssassinZero** [comment]
我把Androidstudio更新到2.3.3之后添加此依赖就报错了
