### ISSUE TITLE
能否增加这些配置项？

### ISSUE THREAD

**Issue by iwgang** [mrfluency/Time-Selector#2]
控件很实用，感谢

回到问题，能否增加下列配置项，好让控件定制化更强
1. 滚动后闪动开关，闪动效果不错，但有些项目中使用还是有些影响整体体验 ？
2. 文字颜色能否自定义设置？
3. 构造时能否可以不传具体时间，默认会有个区间的时间，如1970 - 2050?
4. 回调handle方法中的参数能否增加个如RawDate对象bean，里面存储的是int y, int m ....?

要求有点多，望见谅 ^ ^

**Comment by iwgang** [comment]
另外，能否设置一个默认显示的时间 ^ ^

**Comment by BurnieLiu** [comment]
1235 明天有时间写一下。 4这个，我考虑返回一个calendar吧，需要的话自己可以在回调中给bean赋值。

**Comment by iwgang** [comment]
@mrfluency nice

**Comment by Elieen73** [comment]
非常赞！！文字颜色可以自定义设置了吗

**Comment by Elieen73** [comment]
是否可以再写一个只要年和月的 正好需要了  谢谢啦~
