### ISSUE TITLE
库里没有吗？

### ISSUE THREAD

**Issue by mumu1071** [mrfluency/Time-Selector#3]
android studio 中加入compile 'com.feezu.liuli:timeselector:1.0.8+'

Error:(23, 12) Failed to resolve: com.feezu.liuli:timeselector:1.0.8+

**Comment by BurnieLiu** [comment]
1.1.1+

**Comment by mumu1071** [comment]
还是没有的呐？难道是网络问题

**Comment by mumu1071** [comment]
应该是网络问题了，fresco弄不下来呐

**Comment by BurnieLiu** [comment]
是jcenter吗 没问题啊

**Comment by mumu1071** [comment]
是网络问题，我把源码放入项目里了。如果能支持快速滑动就更好了。就是根据手势的速度决定滚动的多少

**Comment by BurnieLiu** [comment]
好主意 靠你啦 啊
